name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag casual-cli:$(date +%s)
    - name: Publish the Docker image
      run: docker push casualdevelopment/casual-cli:$(date +%s)
